import { Activity } from '@/types/activity';

export const MOCK_ACTIVITIES: Activity[] = [
  // MIND CATEGORY
  {
    id: 'box-breathing',
    title: 'Box Breathing',
    description: 'Equal 4-second cycles of inhaling, holding, exhaling, and holding to restore steady calm.',
    category: 'mind',
    duration_minutes: 2,
    supported_moods: ['overwhelmed', 'mentally_tired', 'restless'],
    supported_intentions: ['reset', 'focus'],
    why_it_helps: 'Equalized breathing patterns balance your autonomic nervous system and reduce physical tension.',
    experience_type: 'interactive',
    is_interactive: true,
  },
  {
    id: 'grounding-54321',
    title: '5-4-3-2-1 Sensory Grounding',
    description: 'A guided step-by-step sensory technique to anchor your attention in physical reality.',
    category: 'mind',
    duration_minutes: 5,
    supported_moods: ['overwhelmed', 'restless'],
    supported_intentions: ['reset', 'focus', 'reflect'],
    why_it_helps: 'Directs your attention away from racing thoughts and back to immediate sensory experience.',
    experience_type: 'guided-steps',
    instructions: [
      'Look around your room and quietly name 5 distinct objects you can see.',
      'Notice 4 physical sensations you can feel right now (e.g., feet pressing against floor, air on skin).',
      'Listen closely and identify 3 subtle ambient sounds around you.',
      'Notice 2 scents or pleasant physical textures near your space.',
      'Take 1 deep breath and acknowledge 1 grounding thought.',
    ],
  },
  {
    id: 'focus-reset',
    title: 'Cognitive Focus Reset',
    description: 'A 20-minute structured timed pause to clear working memory before beginning a major task.',
    category: 'mind',
    duration_minutes: 20,
    supported_moods: ['overwhelmed', 'mentally_tired', 'bored'],
    supported_intentions: ['focus', 'reset'],
    why_it_helps: 'Allows your brain to consolidate recent information and clear mental bandwidth.',
    experience_type: 'timed',
    instructions: [
      'Close unnecessary tabs and rest your eyes.',
      'Focus on slow, natural breathing while the countdown timer runs.',
      'Allow your mind to rest cleanly without checking notifications.',
    ],
  },

  // BODY CATEGORY
  {
    id: 'desk-reset',
    title: 'Desk Reset Stretch',
    description: 'A 2-minute posture sequence to release upper body tightness and neck strain.',
    category: 'body',
    duration_minutes: 2,
    supported_moods: ['low_energy', 'mentally_tired'],
    supported_intentions: ['move', 'reset'],
    why_it_helps: 'Releases muscular tightness caused by seated posture and increases oxygen flow to your brain.',
    experience_type: 'guided-steps',
    instructions: [
      'Sit tall at the front edge of your chair with feet flat on the floor.',
      'Roll your shoulders backward 5 times in slow, gentle circles.',
      'Tilt your right ear toward your right shoulder for 3 deep breaths. Repeat on the left side.',
      'Interlace fingers, reach arms overhead, and take 3 deep belly breaths.',
    ],
  },
  {
    id: 'simple-stretch',
    title: 'Full Body Standing Stretch',
    description: 'Stand up and guide your body through gentle spine and posture-opening movements.',
    category: 'body',
    duration_minutes: 10,
    supported_moods: ['low_energy', 'restless', 'mentally_tired'],
    supported_intentions: ['move', 'reset'],
    why_it_helps: 'Reverses slump posture and re-energizes your circulatory system.',
    experience_type: 'guided-steps',
    instructions: [
      'Stand up from your desk and step into an open space.',
      'Hinge at your hips and let your torso hang loosely toward your feet for 45 seconds.',
      'Slowly roll up one vertebra at a time, reach arms overhead, and gently lean back.',
      'Place hands on lower back and open your chest to the ceiling for 4 deep breaths.',
      'Walk slowly around your room for 1 minute while keeping your breath steady.',
    ],
  },
  {
    id: 'short-walk',
    title: 'Mindful Step Walk',
    description: 'A timed 10-minute screen-free walk to change your physical environment.',
    category: 'body',
    duration_minutes: 10,
    supported_moods: ['restless', 'bored', 'low_energy'],
    supported_intentions: ['move', 'reset', 'focus'],
    why_it_helps: 'Rhythmic physical movement changes your vantage point and boosts mental clarity.',
    experience_type: 'timed',
    instructions: [
      'Step away from all screens and walk at a comfortable pace.',
      'Pay attention to your feet making steady contact with the ground.',
      'Pour yourself a glass of water before returning to your desk.',
    ],
  },

  // CREATIVITY CATEGORY
  {
    id: 'observation-prompt',
    title: 'Physical Object Observation',
    description: 'Examine a physical object near your desk and jot down subtle details.',
    category: 'creative',
    duration_minutes: 5,
    supported_moods: ['bored', 'low_energy'],
    supported_intentions: ['create', 'focus'],
    why_it_helps: 'Engages visual pattern recognition and sparks quiet curiosity without digital stimulation.',
    experience_type: 'writing-prompt',
    prompt_question: 'Pick up one object near you (a pen, key, plant leaf, or cup). Examine its texture, weight, and shadows. What subtle details do you notice that you never saw before?',
  },
  {
    id: 'micro-journal',
    title: 'Micro Journaling',
    description: 'Offload your thoughts onto screen or paper to declutter mental RAM.',
    category: 'creative',
    duration_minutes: 5,
    supported_moods: ['overwhelmed', 'mentally_tired', 'bored'],
    supported_intentions: ['reflect', 'create', 'reset'],
    why_it_helps: 'Writing externalizes mental noise and helps organize unformed thoughts.',
    experience_type: 'writing-prompt',
    prompt_question: 'What is one main thought or task occupying your mind right now? Write a few sentences to clear it out.',
  },

  // REFLECTION CATEGORY
  {
    id: 'pause-and-notice',
    title: 'Pause and Notice',
    description: 'A 2-minute quick guided reflection asking 2 gentle questions about your current state.',
    category: 'reflection',
    duration_minutes: 2,
    supported_moods: ['overwhelmed', 'mentally_tired'],
    supported_intentions: ['reflect', 'reset'],
    why_it_helps: 'Helps cultivate self-awareness of physical and mental state without judgment.',
    experience_type: 'guided-reflection',
    reflection_questions: [
      'Where in your body are you holding physical tension right now?',
      'What is one thing you can let go of for the next hour?',
    ],
  },
  {
    id: 'three-things-noticed',
    title: 'Three Things I Noticed',
    description: 'A 5-minute reflection walking through 3 guiding questions about your day.',
    category: 'reflection',
    duration_minutes: 5,
    supported_moods: ['bored', 'restless', 'mentally_tired'],
    supported_intentions: ['reflect', 'create'],
    why_it_helps: 'Shifts cognitive focus from passive intake to conscious appreciation.',
    experience_type: 'guided-reflection',
    reflection_questions: [
      'What was one moment today where you felt engaged or at ease?',
      'What is something in your immediate space that brings you comfort?',
      'What is a simple, realistic intention for your next task?',
    ],
  },
];
